import greenLeaf from "../../../assets/img/greenLeaf.jpg";
import tandooriFlames from "../../../assets/img/tandooriFlames.jpg";
import royalBiryani from "../../../assets/img/royalBiryani.jpeg";
import shanghaiExpress from "../../../assets/img/shanghaiExpress.png";
import arabianNights from "../../../assets/img/arabianNights.jpg";

const restaurantsData = [
  {
    id: 1,
    name: "Green Leaf Veg Restaurant",
    category: "Vegetarian",
    fullAddress: "123 MG Road, Andheri West, Mumbai, India",
    duration: "30-40 mins",
    rating: 4.5,
    image: greenLeaf,
    latitude: 19.1197,
    longitude: 72.8465,
    distance: 2.1,
    deliveryTime: 35,
    happyHours: false,
    drinksNight: false,
  },
  {
    id: 2,
    name: "Tandoori Flames",
    category: "Indian",
    fullAddress: "45 Connaught Place, New Delhi, India",
    duration: "25-35 mins",
    rating: 4.2,
    image: tandooriFlames,
    latitude: 28.6315,
    longitude: 77.2167,
    distance: 5.4,
    deliveryTime: 30,
    happyHours: true,
    drinksNight: true,
  },
  {
    id: 3,
    name: "Royal Biryani House",
    category: "Biryani",
    fullAddress: "678 Charminar Road, Hyderabad, India",
    duration: "35-45 mins",
    rating: 4.8,
    image: royalBiryani,
    latitude: 17.3616,
    longitude: 78.4747,
    distance: 8.2,
    deliveryTime: 40,
    happyHours: false,
    drinksNight: true,
  },
  {
    id: 4,
    name: "Shanghai Express",
    category: "Chinese",
    fullAddress: "12 Brigade Road, Bangalore, India",
    duration: "20-30 mins",
    rating: 4.3,
    image: shanghaiExpress,
    latitude: 12.9716,
    longitude: 77.5946,
    distance: 1.6,
    deliveryTime: 25,
    happyHours: true,
    drinksNight: false,
  },
  {
    id: 5,
    name: "Arabian Nights",
    category: "Arab",
    fullAddress: "56 Marina Beach Road, Chennai, India",
    duration: "40-50 mins",
    rating: 4.6,
    image: arabianNights,
    latitude: 13.0491,
    longitude: 80.2824,
    distance: 9.3,
    deliveryTime: 45,
    happyHours: false,
    drinksNight: false,
  },
];

export default restaurantsData;
