const blogData = [
    {
      id: 1,
      image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      title: "10 Quick and Easy Breakfast Recipes",
      publishDate: "2024-12-01",
      author: "John Doe",
      location: "New York, USA",
      desc: "Start your day with these delicious and time-saving breakfast recipes that everyone will love.",
      likes: 120,
      comments: 18,
    },
    {
      id: 2,
      image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      title: "Top 5 Vegan Dishes to Try This Winter",
      publishDate: "2024-11-28",
      author: "Jane Smith",
      location: "Berlin, Germany",
      desc: "Warm up this winter with these flavorful and healthy vegan dishes perfect for the season.",
      likes: 98,
      comments: 12,
    },
    {
      id: 3,
      image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      title: "The Secret to Perfect Pasta",
      publishDate: "2024-11-20",
      author: "Chef Alex",
      location: "Rome, Italy",
      desc: "Discover the tips and tricks professional chefs use to make the perfect pasta at home.",
      likes: 185,
      comments: 25,
    },
    {
      id: 4,
      image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      title: "5 Desserts You Can Make in Under 15 Minutes",
      publishDate: "2024-12-05",
      author: "Emily Turner",
      location: "Paris, France",
      desc: "Satisfy your sweet tooth with these quick and easy dessert recipes that require minimal effort.",
      likes: 142,
      comments: 20,
    },
    {
      id: 5,
      image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      title: "How to Create the Ultimate Cheese Board",
      publishDate: "2024-11-30",
      author: "Sophia Lee",
      location: "Amsterdam, Netherlands",
      desc: "Impress your guests with a stunning cheese board using these simple tips and tricks.",
      likes: 110,
      comments: 15,
    },
    {
      id: 6,
      image: "https://images.unsplash.com/photo-1543353071-873f17a7a088?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      title: "The Best Street Foods Around the World",
      publishDate: "2024-12-08",
      author: "Michael Carter",
      location: "Bangkok, Thailand",
      desc: "Take your taste buds on a global journey with these iconic and flavorful street foods.",
      likes: 210,
      comments: 35,
    },
  ];
  
  export default blogData;
  